In [543]:
import pandas as pd
import numpy as np

In [544]:
df=pd.read_csv("Bengaluru_House_Data.csv")

In [545]:
df.shape

(13320, 9)

In [546]:
df.head()

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00

In [547]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   area_type     13320 non-null  object
 1   availability  13320 non-null  object
 2   location      13319 non-null  object
 3   size          13304 non-null  object
 4   society       7818 non-null   object
 5   total_sqft    13320 non-null  object
 6   bath          13247 non-null  float64
 7   balcony       12711 non-null  float64
 8   price         13320 non-null  float64
dtypes: float64(3), object(6)
memory usage: 936.7+ KB

In [548]:
df.sample(20)

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
2466,Built-up Area,Ready To Move,Amruthahalli,2 BHK,NaN,924,2.0,1.0,45.000
6502,Super built-up Area,Ready To Move,Ganga Nagar,3 BHK,NaN,1480,2.0,2.0,125.000
9694,Super built-up Area,Ready To Move,Bharathi Nagar,2 BHK,ReudePr,1349,2.0,2.0,56.700
10019,Plot Area,Ready To Move,Thyagaraja Nagar,5 Bedroom,NaN,570,5.0,0.0,80.000
11622,Super built-up Area,Ready To Move,Anantapuram,3 BHK,GKiewke,1495,2.0,1.0,63.000
12625,Plot Area,Ready To Move,Kengeri Satellite Town,4 Bedroom,NaN,650,2.0,1.0,58.000
12265,Super built-up Area,18-May,Bhoganhalli,2 BHK,Rosha I,1277,2.0,1.0,79.890
8041,Super built-up Area,18-Aug,Ramagondanahalli,2 BHK,ViistLa,1251,2.0,1.0,50.000
7747,Super built-up Area,18-Nov,Thanisandra,1 BHK,Bhe 2ko,620 - 934,1.0,0.0,38.535
11005,Super built-up Area,18-Mar,8th Phase JP Nagar,2 BHK,NaN,1245,2.0,1.0,59.000
8599,Super built-up Area,18-Aug,LB Shastri Nagar,2 BHK,NaN,1250,2.0,2.0,48.500
428,Super built-up Area,Ready To Move,Samethanahalli,2 BHK,SPontna,1069,2.0,1.0,55.000
11510,Super built-up Area,Ready To Move,Uttarahalli,3 BHK,SLnssPr,1245,2.0,2.0,43.580
11272,Built-up Area,Ready To Move,Sidedahalli,2 BHK,NaN,900,2.0,0.0,25.000
13202,Built-up Area,Ready To Move,CV Raman Nagar,2 BHK,NaN,1310,2.0,1.0,62.000
13299,Super built-up Area,18-Dec,Whitefield,4 BHK,Prtates,2830 - 2882,5.0,0.0,154.500
6010,Built-up Area,18-Feb,Escorts Colony,5 BHK,NaN,2400,5.0,2.0,93.000
1004,Super built-up Area,Ready To Move,ITPL,3 BHK,NaN,1548,3.0,2.0,89.500
11516,Super built-up Area,Ready To Move,7th Phase JP Nagar,3 BHK,BriumMi,2100,3.0,2.0,200.000
7176,Super built-up Area,Ready To Move,Hoskote,3 BHK,Sohti S,1069,2.0,NaN,38.000

In [549]:
# Null Values

In [550]:
df.isnull().sum()

area_type          0
availability       0
location           1
size              16
society         5502
total_sqft         0
bath              73
balcony          609
price              0
dtype: int64

In [551]:
# what are the things to be removed
# availability area_type society balcony
df.drop(columns=["availability","area_type","society","balcony"],inplace=True)

In [552]:
df.shape

(13320, 5)

In [553]:
df.head()

                   location       size total_sqft  bath   price
0  Electronic City Phase II      2 BHK       1056   2.0   39.07
1          Chikka Tirupathi  4 Bedroom       2600   5.0  120.00
2               Uttarahalli      3 BHK       1440   2.0   62.00
3        Lingadheeranahalli      3 BHK       1521   3.0   95.00
4                  Kothanur      2 BHK       1200   2.0   51.00

In [554]:
df.describe()

               bath         price
count  13247.000000  13320.000000
mean       2.692610    112.565627
std        1.341458    148.971674
min        1.000000      8.000000
25%        2.000000     50.000000
50%        2.000000     72.000000
75%        3.000000    120.000000
max       40.000000   3600.000000

In [555]:
# Checking for null values
df.isnull().sum()

location       1
size          16
total_sqft     0
bath          73
price          0
dtype: int64

In [556]:
df.dropna(inplace=True)

In [557]:
df.head()

                   location       size total_sqft  bath   price
0  Electronic City Phase II      2 BHK       1056   2.0   39.07
1          Chikka Tirupathi  4 Bedroom       2600   5.0  120.00
2               Uttarahalli      3 BHK       1440   2.0   62.00
3        Lingadheeranahalli      3 BHK       1521   3.0   95.00
4                  Kothanur      2 BHK       1200   2.0   51.00

In [558]:
df.shape

(13246, 5)

In [559]:
df.isnull().sum()

location      0
size          0
total_sqft    0
bath          0
price         0
dtype: int64

In [560]:
df["bhk"]=df["size"].apply(lambda x: int(x.split()[0]))

In [561]:
df.head()

                   location       size total_sqft  bath   price  bhk
0  Electronic City Phase II      2 BHK       1056   2.0   39.07    2
1          Chikka Tirupathi  4 Bedroom       2600   5.0  120.00    4
2               Uttarahalli      3 BHK       1440   2.0   62.00    3
3        Lingadheeranahalli      3 BHK       1521   3.0   95.00    3
4                  Kothanur      2 BHK       1200   2.0   51.00    2

In [562]:
df["bhk"].unique()

array([ 2,  4,  3,  6,  1,  8,  7,  5, 11,  9, 27, 10, 19, 16, 43, 14, 12,
       13, 18], dtype=int64)

In [563]:
df[df["bhk"] > 20]

                       location        size total_sqft  bath  price  bhk
1718  2Electronic City Phase II      27 BHK       8000  27.0  230.0   27
4684                Munnekollal  43 Bedroom       2400  40.0  660.0   43

In [564]:
df["total_sqft"].unique()

array(['1056', '2600', '1440', ..., '1133 - 1384', '774', '4689'],
      dtype=object)

In [565]:
df["total_sqft"].info()

<class 'pandas.core.series.Series'>
Index: 13246 entries, 0 to 13319
Series name: total_sqft
Non-Null Count  Dtype
--------------  -----
13246 non-null  object
dtypes: object(1)
memory usage: 207.0+ KB

In [566]:
def convert_total_sqft(x):
    num=x.split("-")
    if len(num) == 2:
        return float((float(num[0])+float(num[1]))//2)
    try:
        return float(x)
    except:
        return None

In [567]:
convert_total_sqft("4323 . hello")

In [568]:
df["total_sqft"]=df["total_sqft"].apply(convert_total_sqft)

In [569]:
df.head()

                   location       size  total_sqft  bath   price  bhk
0  Electronic City Phase II      2 BHK      1056.0   2.0   39.07    2
1          Chikka Tirupathi  4 Bedroom      2600.0   5.0  120.00    4
2               Uttarahalli      3 BHK      1440.0   2.0   62.00    3
3        Lingadheeranahalli      3 BHK      1521.0   3.0   95.00    3
4                  Kothanur      2 BHK      1200.0   2.0   51.00    2

In [570]:
df["total_sqft"].unique()

array([1056., 2600., 1440., ..., 2758.,  774., 4689.])

In [571]:
df4=df.copy()

In [572]:
df.head()

                   location       size  total_sqft  bath   price  bhk
0  Electronic City Phase II      2 BHK      1056.0   2.0   39.07    2
1          Chikka Tirupathi  4 Bedroom      2600.0   5.0  120.00    4
2               Uttarahalli      3 BHK      1440.0   2.0   62.00    3
3        Lingadheeranahalli      3 BHK      1521.0   3.0   95.00    3
4                  Kothanur      2 BHK      1200.0   2.0   51.00    2

# Feature Engineering

In [574]:
df["price_per_sqft"]=df["price"]*100000 / df["total_sqft"]

In [575]:
df.head()

,location,size,total_sqft,bath,price,bhk,price_per_sqft
0,Electronic City Phase II,2 BHK,1056.0,2.0,39.07,2,3699.810606
1,Chikka Tirupathi,4 Bedroom,2600.0,5.0,120.00,4,4615.384615
2,Uttarahalli,3 BHK,1440.0,2.0,62.00,3,4305.555556
3,Lingadheeranahalli,3 BHK,1521.0,3.0,95.00,3,6245.890861
4,Kothanur,2 BHK,1200.0,2.0,51.00,2,4250.000000

In [576]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 13246 entries, 0 to 13319
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   location        13246 non-null  object
 1   size            13246 non-null  object
 2   total_sqft      13200 non-null  float64
 3   bath            13246 non-null  float64
 4   price           13246 non-null  float64
 5   bhk             13246 non-null  int64
 6   price_per_sqft  13200 non-null  float64
dtypes: float64(4), int64(1), object(2)
memory usage: 827.9+ KB

In [577]:
len(df["location"].unique())

1304

In [578]:
df["location"].apply(lambda x: x.strip())

0        Electronic City Phase II
1                Chikka Tirupathi
2                     Uttarahalli
3              Lingadheeranahalli
4                        Kothanur
                   ...
13315                  Whitefield
13316               Richards Town
13317       Raja Rajeshwari Nagar
13318             Padmanabhanagar
13319                Doddathoguru
Name: location, Length: 13246, dtype: object

In [579]:
location_stats=df.groupby('location')["location"].agg('count').sort_values(ascending=False)
location_stats

location
Whitefield             534
Sarjapur  Road         392
Electronic City        302
Kanakpura Road         266
Thanisandra            233
                      ...
 Banaswadi               1
Kanakadasa Layout        1
Kanakapur main road      1
Kanakapura  Rod          1
whitefiled               1
Name: location, Length: 1304, dtype: int64

In [580]:
location_stats_less_than_10=location_stats[location_stats <=10]

In [581]:
len(df["location"].unique())

1304

In [582]:
df["location"]=df["location"].apply(lambda x: "other" if x in location_stats_less_than_10 else x)

In [583]:
df.head()

,location,size,total_sqft,bath,price,bhk,price_per_sqft
0,Electronic City Phase II,2 BHK,1056.0,2.0,39.07,2,3699.810606
1,Chikka Tirupathi,4 Bedroom,2600.0,5.0,120.00,4,4615.384615
2,Uttarahalli,3 BHK,1440.0,2.0,62.00,3,4305.555556
3,Lingadheeranahalli,3 BHK,1521.0,3.0,95.00,3,6245.890861
4,Kothanur,2 BHK,1200.0,2.0,51.00,2,4250.000000

In [584]:
df.sample(5)

,location,size,total_sqft,bath,price,bhk,price_per_sqft
12408,Jakkur,3 BHK,3295.0,3.0,310.0,3,9408.194234
12215,Banaswadi,6 Bedroom,1200.0,6.0,220.0,6,18333.333333
1235,Yelahanka New Town,1 BHK,500.0,1.0,20.0,1,4000.000000
11890,Thanisandra,2 BHK,965.0,2.0,54.0,2,5595.854922
7037,Harlur,2 BHK,1331.0,2.0,88.0,2,6611.570248

In [585]:
df["total_sqft"].describe()

count    13200.000000
mean      1555.300163
std       1237.323344
min          1.000000
25%       1100.000000
50%       1275.000000
75%       1672.000000
max      52272.000000
Name: total_sqft, dtype: float64

In [586]:
df.sample(5)

,location,size,total_sqft,bath,price,bhk,price_per_sqft
5390,Garudachar Palya,2 BHK,1060.0,2.0,48.50,2,4575.471698
1832,Banashankari,3 Bedroom,600.0,3.0,100.00,3,16666.666667
1821,Sarjapur,3 Bedroom,NaN,3.0,76.00,3,NaN
8133,Padmanabhanagar,3 BHK,1350.0,3.0,71.55,3,5300.000000
12859,Garudachar Palya,3 BHK,1325.0,2.0,60.00,3,4528.301887

# Outlier Detection

In [588]:
df[df["total_sqft"]/df.bhk < 300]

,location,size,total_sqft,bath,price,bhk,price_per_sqft
9,other,6 Bedroom,1020.0,6.0,370.0,6,36274.509804
45,HSR Layout,8 Bedroom,600.0,9.0,200.0,8,33333.333333
58,Murugeshpalya,6 Bedroom,1407.0,4.0,150.0,6,10660.980810
68,other,8 Bedroom,1350.0,7.0,85.0,8,6296.296296
70,other,3 Bedroom,500.0,3.0,100.0,3,20000.000000
...,...,...,...,...,...,...,...
13277,other,7 Bedroom,1400.0,7.0,218.0,7,15571.428571
13279,other,6 Bedroom,1200.0,5.0,130.0,6,10833.333333
13281,Margondanahalli,5 Bedroom,1375.0,5.0,125.0,5,9090.909091
13303,Vidyaranyapura,5 Bedroom,774.0,5.0,70.0,5,9043.927649
13311,Ramamurthy Nagar,7 Bedroom,1500.0,9.0,250.0,7,16666.666667

In [589]:
df=df[~ (df["total_sqft"]/df.bhk < 300)]

In [590]:
df.shape

(12502, 7)

In [591]:
df["price_per_sqft"].describe()

count     12456.000000
mean       6308.513707
std        4168.123545
min         267.829813
25%        4210.526316
50%        5294.117647
75%        6916.666667
max      176470.588235
Name: price_per_sqft, dtype: float64

In [592]:
df.shape

(12502, 7)

In [593]:
# Removing the price per square foot outliers
# mean-st and mean+st in normal distribution
def remove_pps_outliers(df1):
    df_out = pd.DataFrame()
    for key, subdf in df1.groupby('location'):
        m = np.mean(subdf.price_per_sqft)
        st = np.std(subdf.price_per_sqft)
        reduced_df = subdf[(subdf.price_per_sqft>(m-st)) & (subdf.price_per_sqft<=(m+st))]
        df_out = pd.concat([df_out,reduced_df], ignore_index=True)
    return df_out

In [594]:
df1=remove_pps_outliers(df)

In [595]:
df1.shape

(10244, 7)

In [596]:
df1[df1.bath > df1.bhk + 2]

           location       size  total_sqft  bath   price  bhk  price_per_sqft
1637  Chikkabanavar  4 Bedroom      2460.0   7.0    80.0    4     3252.032520
5232     Nagasandra  4 Bedroom      7000.0   8.0   450.0    4     6428.571429
6702    Thanisandra      3 BHK      1806.0   6.0   116.0    3     6423.034330
8405          other      6 BHK     11338.0   9.0  1000.0    6     8819.897689

In [597]:
df1=df1[df1.bath < df1.bhk + 2]

df1.shape

In [662]:
df1=df1.drop(columns=["size" , "price_per_sqft"])

In [664]:
df1.shape

(10150, 5)

In [666]:
df1.head()

               location  total_sqft  bath  price  bhk
0   Devarachikkanahalli      1250.0   2.0   44.0    3
1   Devarachikkanahalli      1250.0   2.0   40.0    2
2   Devarachikkanahalli      1200.0   2.0   83.0    2
3   Devarachikkanahalli      1170.0   2.0   40.0    2
4   Devarachikkanahalli      1425.0   2.0   65.0    3

In [670]:
df1.sample(5)

              location  total_sqft  bath   price  bhk
4338  Kaval Byrasandra      1200.0   2.0   49.50    2
2047   Electronic City      1128.0   2.0   64.00    2
8124             other      1600.0   4.0  125.00    5
3183             Hoodi      1108.0   2.0   74.23    2
8726             other       833.0   1.0   49.00    1

# Model Training

In [739]:
# Applying the one hot encoding
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ohe=OneHotEncoder()
categorical_features = ["location"]
column_trans=ColumnTransformer(transformers=[
    ("cat",ohe,categorical_features),
],remainder="passthrough")

In [741]:
column_trans

ColumnTransformer(remainder='passthrough',
                  transformers=[('cat', OneHotEncoder(), ['location'])])

In [799]:
from sklearn.pipeline import make_pipeline
from xgboost import XGBRegressor
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVR
svr=SVR()
lr=LinearRegression()
xgb=XGBRegressor()
pipe=make_pipeline(column_trans,svr)

In [801]:
df1=df1[["location","total_sqft","bath","bhk","price"]]

In [803]:
x=df1.iloc[:,0:-1]
y=df1.iloc[:,-1]

In [805]:
x

                   location  total_sqft  bath  bhk
0       Devarachikkanahalli      1250.0   2.0    3
1       Devarachikkanahalli      1250.0   2.0    2
2       Devarachikkanahalli      1200.0   2.0    2
3       Devarachikkanahalli      1170.0   2.0    2
4       Devarachikkanahalli      1425.0   2.0    3
...                     ...         ...   ...  ...
10239                 other      1353.0   2.0    2
10240                 other       812.0   1.0    1
10241                 other      1440.0   2.0    3
10242                 other      1075.0   2.0    2
10243                 other      3600.0   5.0    4

[10150 rows x 4 columns]

In [806]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.2,random_state=10)

In [809]:
xtrain

                         location  total_sqft  bath  bhk
5469         Poorna Pragna Layout       965.0   2.0    2
5077                 Marathahalli      1360.0   2.0    2
974             Bannerghatta Road      1470.0   2.0    3
9531                        other      1108.0   2.0    2
531                     Ardendale      1723.0   3.0    3
...                           ...         ...   ...  ...
9457                        other      1720.0   3.0    3
7360                   Whitefield       630.0   1.0    1
1353  Bommasandra Industrial Area      1090.0   2.0    2
7362                   Whitefield      1200.0   3.0    3
1298                Bisuvanahalli      1075.0   2.0    3

[8120 rows x 4 columns]

In [810]:
ytrain

5469     48.00
5077    101.00
974      85.00
9531     48.00
531      95.00
         ...
9457     83.00
7360     32.15
1353     31.48
7362     57.15
1298     48.00
Name: price, Length: 8120, dtype: float64

In [812]:
pipe.fit(xtrain,ytrain)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('cat', OneHotEncoder(),
                                                  ['location'])])),
                ('svr', SVR())])

In [814]:
ypred=pipe.predict(xtest)

In [815]:
from sklearn.metrics import r2_score
r2_score(ytest,ypred)

0.40299102983440793

In [823]:
!pip install optuna

Requirement already satisfied: optuna in d:\anaconda\lib\site-packages (4.1.0)
Requirement already satisfied: alembic>=1.5.0 in d:\anaconda\lib\site-packages (from optuna) (1.14.0)
Requirement already satisfied: colorlog in d:\anaconda\lib\site-packages (from optuna) (6.9.0)
Requirement already satisfied: numpy in d:\anaconda\lib\site-packages (from optuna) (1.26.4)
Requirement already satisfied: packaging>=20.0 in d:\anaconda\lib\site-packages (from optuna) (23.2)
Requirement already satisfied: sqlalchemy>=1.4.2 in d:\anaconda\lib\site-packages (from optuna) (2.0.30)
Requirement already satisfied: tqdm in d:\anaconda\lib\site-packages (from optuna) (4.66.4)
Requirement already satisfied: PyYAML in d:\anaconda\lib\site-packages (from optuna) (6.0.1)
Requirement already satisfied: Mako in d:\anaconda\lib\site-packages (from alembic>=1.5.0->optuna) (1.3.8)
Requirement already satisfied: typing-extensions>=4 in d:\anaconda\lib\site-packages (from alembic>=1.5.0->optuna) (4.11.0)
Requirement already satisfied: greenlet!=0.4.17 in d:\anaconda\lib\site-packages (from sqlalchemy>=1.4.2->optuna) (3.0.1)
Requirement already satisfied: colorama in d:\anaconda\lib\site-packages (from colorlog->optuna) (0.4.6)
Requirement already satisfied: MarkupSafe>=0.9.2 in d:\anaconda\lib\site-packages (from Mako->alembic>=1.5.0->optuna) (2.1.3)

In [877]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import Ridge, Lasso, ElasticNet
def objective(trial):
    # n_estimators=trial.suggest_int('n_estimators',50,200)
    # max_depth=trial.suggest_int('max_depth',3,20)
    # model=RandomForestRegressor(n_estimators=n_estimators,max_depth=max_depth,
    # random_state=42)
    # param_grid = {
    #     "n_estimators": trial.suggest_int("n_estimators", 100, 1000, step=50),
    #     "max_depth": trial.suggest_int("max_depth", 3, 15),
    #     "learning_rate": trial.suggest_loguniform("learning_rate", 0.01, 0.3),
    #     "subsample": trial.suggest_uniform("subsample", 0.5, 1.0),
    #     "colsample_bytree": trial.suggest_uniform("colsample_bytree", 0.5, 1.0),
    #     "reg_alpha": trial.suggest_loguniform("reg_alpha", 1e-8, 1.0),
    #     "reg_lambda": trial.suggest_loguniform("reg_lambda", 1e-8, 1.0),
    #     "min_child_weight": trial.suggest_int("min_child_weight", 1, 10),
    #     "gamma": trial.suggest_loguniform("gamma", 1e-8, 1.0),
    # }
    # model = XGBRegressor(**param_grid, random_state=10)
    model_type = trial.suggest_categorical("model_type", ["Ridge", "Lasso", "ElasticNet"])
    
    # Define hyperparameter search space
    if model_type == "Ridge":
        params = {
            "alpha": trial.suggest_loguniform("alpha", 1e-5, 10),
        }
        model = Ridge(**params)
    elif model_type == "Lasso":
        params = {
            "alpha": trial.suggest_loguniform("alpha", 1e-5, 10),
        }
        model = Lasso(**params)
    elif model_type == "ElasticNet":
        params = {
            "alpha": trial.suggest_loguniform("alpha", 1e-5, 10),
            "l1_ratio": trial.suggest_uniform("l1_ratio", 0.0, 1.0),
        }
        model = ElasticNet(**params)
    pipe=make_pipeline(column_trans,model)
    pipe.fit(xtrain,ytrain)
    ypred=pipe.predict(xtest)
    score=r2_score(ytest,ypred)
    return score

In [879]:
import optuna
study=optuna.create_study(direction="maximize",sampler=optuna.samplers.TPESampler())
study.optimize(objective,n_trials=50)

[I 2025-01-17 23:36:16,846] A new study created in memory with name: no-name-76af7c58-e591-4f56-82ff-32efa7305628
C:\Users\pares\AppData\Local\Temp\ipykernel_32912\289640134.py:30: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  "alpha": trial.suggest_loguniform("alpha", 1e-5, 10),
[I 2025-01-17 23:36:16,977] Trial 0 finished with value: 0.6766343466268036 and parameters: {'model_type': 'Lasso', 'alpha': 0.28785006086917575}. Best is trial 0 with value: 0.6766343466268036.
C:\Users\pares\AppData\Local\Temp\ipykernel_32912\289640134.py:35: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  "alpha": trial.suggest_loguniform("alpha", 1e-5, 10),
C:\Users\pares\AppData\Local\Temp\ipykernel_32912\289640134.py:36: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  "l1_ratio": trial.suggest_uniform("l1_ratio", 0.0, 1.0),
[I 2025-01-17 23:36:18,215] Trial 1 finished with value: 0.7634051522353988 and parameters: {'model_type': 'ElasticNet', 'alpha': 0.00025081111059793476, 'l1_ratio': 0.0033010667184706355}. Best is trial 1 with value: 0.7634051522353988.
C:\Users\pares\AppData\Local\Temp\ipykernel_32912\289640134.py:25: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  "alpha": trial.suggest_loguniform("alpha", 1e-5, 10),
[I 2025-01-17 23:36:18,245] Trial 2 finished with value: 0.6172065843279341 and parameters: {'model_type': 'Ridge', 'alpha': 0.001810414555494785}. Best is trial 1 with value: 0.7634051522353988.
C:\Users\pares\AppData\Local\Temp\ipykernel_32912\289640134.py:35: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  "alpha": trial.suggest_loguniform("alpha", 1e-5, 10),
C:\Users\pares\AppData\Local\Temp\ipykernel_32912\289640134.py:36: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  "l1_ratio": trial.suggest_uniform("l1_ratio", 0.0, 1.0),
[I 2025-01-17 23:36:18,605] Trial 3 finished with value: 0.7183394085508251 and parameters: {'model_type': 'ElasticNet', 'alpha': 0.0033648328014855822, 'l1_ratio': 0.4542608030423674}. Best is trial 1 with value: 0.7634051522353988.
C:\Users\pares\AppData\Local\Temp\ipykernel_32912\289640134.py:35: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  "alpha": trial.suggest_loguniform("alpha", 1e-5, 10),
C:\Users\pares\AppData\Local\Temp\ipykernel_32912\289640134.py:36: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  "l1_ratio": trial.suggest_uniform("l1_ratio", 0.0, 1.0),
[I 2025-01-17 23:36:18,859] Trial 4 finished with value: 0.6406643268003847 and parameters: {'model_type': 'ElasticNet', 'alpha': 0.02952273345752127, 'l1_ratio': 0.147701120110042}. Best is trial 1 with value: 0.7634051522353988.
C:\Users\pares\AppData\Local\Temp\ipykernel_32912\289640134.py:25: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  "alpha": trial.suggest_loguniform("alpha", 1e-5, 10),
[I 2025-01-17 23:36:18,891] Trial 5 finished with value: 0.6172065843273752 and parameters: {'model_type': 'Ridge', 'alpha': 0.03052021793727982}. Best is trial 1 with value: 0.7634051522353988.
C:\Users\pares\AppData\Local\Temp\ipykernel_32912\289640134.py:30: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  "alpha": trial.suggest_loguniform("alpha", 1e-5, 10),
[I 2025-01-17 23:36:18,999] Trial 6 finished with value: 0.6406918993054876 and parameters: {'model_type': 'Lasso', 'alpha': 0.38896715161949696}. Best is trial 1 with value: 0.7634051522353988.
C:\Users\pares\AppData\Local\Temp\ipykernel_32912\289640134.py:25: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  "alpha": trial.suggest_loguniform("alpha", 1e-5, 10),
[I 2025-01-17 23:36:19,032] Trial 7 finished with value: 0.617206584327969 and parameters: {'model_type': 'Ridge', 'alpha': 1.2673742222154753e-05}. Best is trial 1 with value: 0.7634051522353988.
C:\Users\pares\AppData\Local\Temp\ipykernel_32912\289640134.py:35: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  "alpha": trial.suggest_loguniform("alpha", 1e-5, 10),
C:\Users\pares\AppData\Local\Temp\ipykernel_32912\289640134.py:36: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  "l1_ratio": trial.suggest_uniform("l1_ratio", 0.0, 1.0),
[I 2025-01-17 23:36:19,241] Trial 8 finished with value: 0.6384018432334749 and parameters: {'model_type': 'ElasticNet', 'alpha': 0.04384116050892738, 'l1_ratio': 0.3896846860306252}. Best is trial 1 with value: 0.7634051522353988.
C:\Users\pares\AppData\Local\Temp\ipykernel_32912\289640134.py:25: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  "alpha": trial.suggest_loguniform("alpha", 1e-5, 10),
[I 2025-01-17 23:36:19,275] Trial 9 finished with value: 0.6172065843279212 and parameters: {'model_type': 'Ridge', 'alpha': 0.0024706853251766263}. Best is trial 1 with value: 0.7634051522353988.
C:\Users\pares\AppData\Local\Temp\ipykernel_32912\289640134.py:35: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  "alpha": trial.suggest_loguniform("alpha", 1e-5, 10),
C:\Users\pares\AppData\Local\Temp\ipykernel_32912\289640134.py:36: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  "l1_ratio": trial.suggest_uniform("l1_ratio", 0.0, 1.0),
D:\Anaconda\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:639: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 220339.9226173805, tolerance: 5149.290881273171
  model = cd_fast.sparse_enet_coordinate_descent(
[I 2025-01-17 23:36:27,320] Trial 10 finished with value: 0.769601921055509 and parameters: {'model_type': 'ElasticNet', 'alpha': 5.273119252208722e-05, 'l1_ratio': 0.9835631001410196}. Best is trial 10 with value: 0.769601921055509.
C:\Users\pares\AppData\Local\Temp\ipykernel_32912\289640134.py:35: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  "alpha": trial.suggest_loguniform("alpha", 1e-5, 10),
C:\Users\pares\AppData\Local\Temp\ipykernel_32912\289640134.py:36: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  "l1_ratio": trial.suggest_uniform("l1_ratio", 0.0, 1.0),
D:\Anaconda\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:639: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 515997.7240574192, tolerance: 5149.290881273171
  model = cd_fast.sparse_enet_coordinate_descent(
[I 2025-01-17 23:36:35,417] Trial 11 finished with value: 0.7696018629897811 and parameters: {'model_type': 'ElasticNet', 'alpha': 3.6200029615580224e-05, 'l1_ratio': 0.9824106113857916}. Best is trial 10 with value: 0.769601921055509.
C:\Users\pares\AppData\Local\Temp\ipykernel_32912\289640134.py:35: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  "alpha": trial.suggest_loguniform("alpha", 1e-5, 10),
C:\Users\pares\AppData\Local\Temp\ipykernel_32912\289640134.py:36: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  "l1_ratio": trial.suggest_uniform("l1_ratio", 0.0, 1.0),
D:\Anaconda\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:639: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 344723.55504998285, tolerance: 5149.290881273171
  model = cd_fast.sparse_enet_coordinate_descent(
[I 2025-01-17 23:36:43,520] Trial 12 finished with value: 0.7696000745140978 and parameters: {'model_type': 'ElasticNet', 'alpha': 1.8391353935287078e-05, 'l1_ratio': 0.959470149259061}. Best is trial 10 with value: 0.769601921055509.
C:\Users\pares\AppData\Local\Temp\ipykernel_32912\289640134.py:35: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  "alpha": trial.suggest_loguniform("alpha", 1e-5, 10),
C:\Users\pares\AppData\Local\Temp\ipykernel_32912\289640134.py:36: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  "l1_ratio": trial.suggest_uniform("l1_ratio", 0.0, 1.0),
[I 2025-01-17 23:36:47,515] Trial 13 finished with value: 0.7695979633345607 and parameters: {'model_type': 'ElasticNet', 'alpha': 0.00016844233543242195, 'l1_ratio': 0.976909296060386}. Best is trial 10 with value: 0.769601921055509.
C:\Users\pares\AppData\Local\Temp\ipykernel_32912\289640134.py:35: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  "alpha": trial.suggest_loguniform("alpha", 1e-5, 10),
C:\Users\pares\AppData\Local\Temp\ipykernel_32912\289640134.py:36: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  "l1_ratio": trial.suggest_uniform("l1_ratio", 0.0, 1.0),
[I 2025-01-17 23:36:51,347] Trial 14 finished with value: 0.7692821951012037 and parameters: {'model_type': 'ElasticNet', 'alpha': 0.00013973054556627867, 'l1_ratio': 0.7348641534512006}. Best is trial 10 with value: 0.769601921055509.
C:\Users\pares\AppData\Local\Temp\ipykernel_32912\289640134.py:35: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  "alpha": trial.suggest_loguniform("alpha", 1e-5, 10),
C:\Users\pares\AppData\Local\Temp\ipykernel_32912\289640134.py:36: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  "l1_ratio": trial.suggest_uniform("l1_ratio", 0.0, 1.0),
D:\Anaconda\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:639: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 100383.79645247106, tolerance: 5149.290881273171
  model = cd_fast.sparse_enet_coordinate_descent(
[I 2025-01-17 23:36:59,581] Trial 15 finished with value: 0.7695375824397198 and parameters: {'model_type': 'ElasticNet', 'alpha': 4.3369346246356454e-05, 'l1_ratio': 0.7174914483341213}. Best is trial 10 with value: 0.769601921055509.
C:\Users\pares\AppData\Local\Temp\ipykernel_32912\289640134.py:30: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  "alpha": trial.suggest_loguniform("alpha", 1e-5, 10),
[I 2025-01-17 23:36:59,672] Trial 16 finished with value: 0.6171982423671708 and parameters: {'model_type': 'Lasso', 'alpha': 4.141510347847424}. Best is trial 10 with value: 0.769601921055509.
C:\Users\pares\AppData\Local\Temp\ipykernel_32912\289640134.py:35: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  "alpha": trial.suggest_loguniform("alpha", 1e-5, 10),
C:\Users\pares\AppData\Local\Temp\ipykernel_32912\289640134.py:36: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  "l1_ratio": trial.suggest_uniform("l1_ratio", 0.0, 1.0),
[I 2025-01-17 23:37:01,371] Trial 17 finished with value: 0.7682258204248493 and parameters: {'model_type': 'ElasticNet', 'alpha': 0.0004288141248549946, 'l1_ratio': 0.7847229081741949}. Best is trial 10 with value: 0.769601921055509.
C:\Users\pares\AppData\Local\Temp\ipykernel_32912\289640134.py:35: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  "alpha": trial.suggest_loguniform("alpha", 1e-5, 10),
C:\Users\pares\AppData\Local\Temp\ipykernel_32912\289640134.py:36: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  "l1_ratio": trial.suggest_uniform("l1_ratio", 0.0, 1.0),
D:\Anaconda\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:639: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 794510.1165306158, tolerance: 5149.290881273171
  model = cd_fast.sparse_enet_coordinate_descent(
[I 2025-01-17 23:37:09,372] Trial 18 finished with value: 0.7695845000397875 and parameters: {'model_type': 'ElasticNet', 'alpha': 3.62375470082661e-05, 'l1_ratio': 0.8726952841715961}. Best is trial 10 with value: 0.769601921055509.
C:\Users\pares\AppData\Local\Temp\ipykernel_32912\289640134.py:30: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  "alpha": trial.suggest_loguniform("alpha", 1e-5, 10),
[I 2025-01-17 23:37:11,875] Trial 19 finished with value: 0.7696259818668109 and parameters: {'model_type': 'Lasso', 'alpha': 0.0006513997323827225}. Best is trial 19 with value: 0.7696259818668109.
C:\Users\pares\AppData\Local\Temp\ipykernel_32912\289640134.py:30: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  "alpha": trial.suggest_loguniform("alpha", 1e-5, 10),
[I 2025-01-17 23:37:13,884] Trial 20 finished with value: 0.7696279268351107 and parameters: {'model_type': 'Lasso', 'alpha': 0.000805358176642265}. Best is trial 20 with value: 0.7696279268351107.
C:\Users\pares\AppData\Local\Temp\ipykernel_32912\289640134.py:30: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  "alpha": trial.suggest_loguniform("alpha", 1e-5, 10),
[I 2025-01-17 23:37:16,016] Trial 21 finished with value: 0.7696274891450802 and parameters: {'model_type': 'Lasso', 'alpha': 0.000759047226627101}. Best is trial 20 with value: 0.7696279268351107.
C:\Users\pares\AppData\Local\Temp\ipykernel_32912\289640134.py:30: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  "alpha": trial.suggest_loguniform("alpha", 1e-5, 10),
[I 2025-01-17 23:37:17,719] Trial 22 finished with value: 0.7696287142741289 and parameters: {'model_type': 'Lasso', 'alpha': 0.000940557692770825}. Best is trial 22 with value: 0.7696287142741289.
C:\Users\pares\AppData\Local\Temp\ipykernel_32912\289640134.py:30: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  "alpha": trial.suggest_loguniform("alpha", 1e-5, 10),
[I 2025-01-17 23:37:18,085] Trial 23 finished with value: 0.7692743509040525 and parameters: {'model_type': 'Lasso', 'alpha': 0.005433462521929317}. Best is trial 22 with value: 0.7696287142741289.
C:\Users\pares\AppData\Local\Temp\ipykernel_32912\289640134.py:30: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  "alpha": trial.suggest_loguniform("alpha", 1e-5, 10),
[I 2025-01-17 23:37:19,477] Trial 24 finished with value: 0.7696288887276507 and parameters: {'model_type': 'Lasso', 'alpha': 0.0011472995970399965}. Best is trial 24 with value: 0.7696288887276507.
C:\Users\pares\AppData\Local\Temp\ipykernel_32912\289640134.py:30: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  "alpha": trial.suggest_loguniform("alpha", 1e-5, 10),
[I 2025-01-17 23:37:20,976] Trial 25 finished with value: 0.7696290469660251 and parameters: {'model_type': 'Lasso', 'alpha': 0.0010426541165331523}. Best is trial 25 with value: 0.7696290469660251.
C:\Users\pares\AppData\Local\Temp\ipykernel_32912\289640134.py:30: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  "alpha": trial.suggest_loguniform("alpha", 1e-5, 10),
[I 2025-01-17 23:37:21,281] Trial 26 finished with value: 0.768884827117051 and parameters: {'model_type': 'Lasso', 'alpha': 0.008802571227275046}. Best is trial 25 with value: 0.7696290469660251.

In [881]:
study.best_params

{'model_type': 'Lasso', 'alpha': 0.0010759530759822328}

In [883]:
study.best_trial.value

0.7696290535777641

In [897]:
model = Lasso(alpha=0.0010759530759822328, random_state=20)
pipe=make_pipeline(column_trans,model)
pipe.fit(xtrain,ytrain)
ypred=pipe.predict(xtest)
r2_score(ytest,ypred)

0.7696290535777641

In [899]:
pipe

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('cat', OneHotEncoder(),
                                                  ['location'])])),
                ('lasso', Lasso(alpha=0.0010759530759822328, random_state=20))])

In [901]:
df1.head()

               location  total_sqft  bath  bhk  price
0   Devarachikkanahalli      1250.0   2.0    3   44.0
1   Devarachikkanahalli      1250.0   2.0    2   40.0
2   Devarachikkanahalli      1200.0   2.0    2   83.0
3   Devarachikkanahalli      1170.0   2.0    2   40.0
4   Devarachikkanahalli      1425.0   2.0    3   65.0

In [903]:
df1.shape

(10150, 5)

In [905]:
df1.to_csv("Cleaned_Data.csv")

In [907]:
import pickle
pickle.dump(pipe,open("LinearRegressionModel.pkl","wb"))

In [911]:
df1.head()

               location  total_sqft  bath  bhk  price
0   Devarachikkanahalli      1250.0   2.0    3   44.0
1   Devarachikkanahalli      1250.0   2.0    2   40.0
2   Devarachikkanahalli      1200.0   2.0    2   83.0
3   Devarachikkanahalli      1170.0   2.0    2   40.0
4   Devarachikkanahalli      1425.0   2.0    3   65.0

In [919]:
df1["total_sqft"].max()

30400.0